config/routes.rb
Rails.application.routes.draw do
  resources :encomendas
  resources :moradors
  resources :funcionarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/encomenda.rb
class Encomenda < ApplicationRecord
  has_one :funcionario, dependent: :destroy
  has_one :morador, dependent: :destroy

  validates :remetente, presence: true, length: {in: 5..50}
  validate :data_entrega

  def data_entrega
    if data.present? && data < Date.today
      errors.add(:data, "nao pode ser no passado")
    end
  end
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  has_many :encomendas

  validates :nome, presence: true, length: {in: 5..40}
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :senha, presence:true, confirmation: true, length: {in:8..25}
  validates :senha_confirmation, presence: true
  validate :senha_uppercase, :senha_lower_case, :senha_special_char

  def senha_uppercase
    return if !!senha.match(/\p{Upper}/)
    errors.add(:senha,"deve conter letra maiuscula")
  end

  def senha_lower_case
    return if !!senha.match(/\p{Lower}/)
    errors.add(:senha,"deve conter letra minuscula")
  end

  def senha_special_char
    special = "?<>',?[]}{=-)(*&@^%$#`~{}!"
    regex = /[#{special.gsub(/./){|char| "\\#{char}"}}]/
    return if senha =~ regex
    errors.add(:senha,"deve conter caractere especial (ex: @,$,...)")
  end
end

app/models/morador.rb
class Morador < ApplicationRecord
  has_many :encomendas
  
  validates :nome, presence: true, length: {in: 5..50}
  validates :casanum, presence:true, numericality:true
  validates :bloco, presence: true
  validates :contato, presence: true, numericality:true, length:{minimum: 9}
  validates :cpf, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/encomendas_controller.rb
class EncomendasController < ApplicationController
  before_action :set_encomenda, only: %i[ show edit update destroy ]

  # GET /encomendas or /encomendas.json
  def index
    @encomendas = Encomenda.all
  end

  # GET /encomendas/1 or /encomendas/1.json
  def show
  end

  # GET /encomendas/new
  def new
    @encomenda = Encomenda.new
  end

  # GET /encomendas/1/edit
  def edit
  end

  # POST /encomendas or /encomendas.json
  def create
    @funcionario = Funcionario.find(encomenda_params[:funcionario_id])
    @morador = Morador.find(encomenda_params[:morador_id])
    @encomenda = Encomenda.new(encomenda_params)
    @funcionario.encomendas << @encomenda
    @morador.encomendas << @encomenda
    
    respond_to do |format|
      if @encomenda.save
        format.html { redirect_to @encomenda, notice: "Encomenda was successfully created." }
        format.json { render :show, status: :created, location: @encomenda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @encomenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encomendas/1 or /encomendas/1.json
  def update
    respond_to do |format|
      if @encomenda.update(encomenda_params)
        format.html { redirect_to @encomenda, notice: "Encomenda was successfully updated." }
        format.json { render :show, status: :ok, location: @encomenda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @encomenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encomendas/1 or /encomendas/1.json
  def destroy
    @encomenda.destroy
    respond_to do |format|
      format.html { redirect_to encomendas_url, notice: "Encomenda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encomenda
      @encomenda = Encomenda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def encomenda_params
      params.require(:encomenda).permit(:remetente, :data, :funcionario_id, :morador_id)
    end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :email, :senha, :senha_confirmation)
    end
end

app/controllers/moradors_controller.rb
class MoradorsController < ApplicationController
  before_action :set_morador, only: %i[ show edit update destroy ]

  # GET /moradors or /moradors.json
  def index
    @moradors = Morador.all
  end

  # GET /moradors/1 or /moradors/1.json
  def show
  end

  # GET /moradors/new
  def new
    @morador = Morador.new
  end

  # GET /moradors/1/edit
  def edit
  end

  # POST /moradors or /moradors.json
  def create
    @morador = Morador.new(morador_params)

    respond_to do |format|
      if @morador.save
        format.html { redirect_to @morador, notice: "Morador was successfully created." }
        format.json { render :show, status: :created, location: @morador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @morador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moradors/1 or /moradors/1.json
  def update
    respond_to do |format|
      if @morador.update(morador_params)
        format.html { redirect_to @morador, notice: "Morador was successfully updated." }
        format.json { render :show, status: :ok, location: @morador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @morador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moradors/1 or /moradors/1.json
  def destroy
    @morador.destroy
    respond_to do |format|
      format.html { redirect_to moradors_url, notice: "Morador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morador
      @morador = Morador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def morador_params
      params.require(:morador).permit(:nome, :cpf, :bloco, :casanum, :contato)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encomendas_helper.rb
module EncomendasHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/moradors_helper.rb
module MoradorsHelper
end

app/views/encomendas/_form.html.erb
<%= form_with(model: encomenda) do |form| %>
  <% if encomenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(encomenda.errors.count, "error") %> prohibited this encomenda from being saved:</h2>

      <ul>
        <% encomenda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :remetente %>
    <%= form.text_field :remetente %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.collection_select(:funcionario_id, Funcionario.all, :id, :nome,{:selected => @encomenda.funcionario_id})%>
  </div>

  <div class="field">
    <%= form.label :morador_id %>
    <%= form.collection_select(:morador_id, Morador.all, :id, :nome,{:selected => @encomenda.morador_id})%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/encomendas/edit.html.erb
<h1>Editing Encomenda</h1>

<%= render 'form', encomenda: @encomenda %>

<%= link_to 'Show', @encomenda %> |
<%= link_to 'Back', encomendas_path %>

app/views/encomendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Encomendas</h1>

<table>
  <thead>
    <tr>
      <th>Remetente</th>
      <th>Data</th>
      <th>Funcionario</th>
      <th>Morador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encomendas.each do |encomenda| %>
      <tr>
        <td><%= encomenda.remetente %></td>
        <td><%= encomenda.data %></td>
        <td><%= encomenda.funcionario_id %></td>
        <td><%= encomenda.morador_id %></td>
        <td><%= link_to 'Show', encomenda %></td>
        <td><%= link_to 'Edit', edit_encomenda_path(encomenda) %></td>
        <td><%= link_to 'Destroy', encomenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encomenda', new_encomenda_path %>

app/views/encomendas/new.html.erb
<h1>New Encomenda</h1>

<%= render 'form', encomenda: @encomenda %>

<%= link_to 'Back', encomendas_path %>

app/views/encomendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Remetente:</strong>
  <%= @encomenda.remetente %>
</p>

<p>
  <strong>Data:</strong>
  <%= @encomenda.data %>
</p>

<p>
  <strong>Funcionario:</strong>
  <%= Funcionario.find(@encomenda.funcionario_id).nome %>
</p>

<p>
  <strong>Morador:</strong>
  <%= Morador.find(@encomenda.morador_id).nome %>
</p>

<%= link_to 'Edit', edit_encomenda_path(@encomenda) %> |
<%= link_to 'Back', encomendas_path %>

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.password_field :senha %>
  </div>

  <div class="field">
    <%= form.label :senha_confirmation %>
    <%= form.password_field :senha_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.email %></td>
        <td><%= funcionario.senha %></td>
        <td><%= link_to 'Visualizar', funcionario %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario), id:"e-#{funcionario.nome}"%></td>
        <td><%= link_to 'Deletar', funcionario, id:"d-#{funcionario.nome}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @funcionario.email %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @funcionario.senha %>
</p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteES</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moradors/_form.html.erb
<%= form_with(model: morador) do |form| %>
  <% if morador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(morador.errors.count, "error") %> prohibited this morador from being saved:</h2>

      <ul>
        <% morador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :bloco %>
    <%= form.text_field :bloco %>
  </div>

  <div class="field">
    <%= form.label :casanum %>
    <%= form.text_field :casanum %>
  </div>

  <div class="field">
    <%= form.label :contato %>
    <%= form.text_field :contato %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moradors/edit.html.erb
<h1>Editing Morador</h1>

<%= render 'form', morador: @morador %>

<%= link_to 'Show', @morador %> |
<%= link_to 'Back', moradors_path %>

app/views/moradors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moradors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Bloco</th>
      <th>Casanum</th>
      <th>Contato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moradors.each do |morador| %>
      <tr>
        <td><%= morador.nome %></td>
        <td><%= morador.cpf %></td>
        <td><%= morador.bloco %></td>
        <td><%= morador.casanum %></td>
        <td><%= morador.contato %></td>
        <td><%= link_to 'Show', morador %></td>
        <td><%= link_to 'Edit', edit_morador_path(morador) %></td>
        <td><%= link_to 'Destroy', morador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Morador', new_morador_path %>

app/views/moradors/new.html.erb
<h1>New Morador</h1>

<%= render 'form', morador: @morador %>

<%= link_to 'Back', moradors_path %>

app/views/moradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @morador.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @morador.cpf %>
</p>

<p>
  <strong>Bloco:</strong>
  <%= @morador.bloco %>
</p>

<p>
  <strong>Casanum:</strong>
  <%= @morador.casanum %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @morador.contato %>
</p>

<%= link_to 'Edit', edit_morador_path(@morador) %> |
<%= link_to 'Back', moradors_path %>

app/views/welcome/index.html.erb
<h1>Gerenciamento ES</h1>
<ul>
  <li><%= link_to "Funcionarios", funcionarios_path %></li>
  <li><%= link_to "Moradores", moradors_path %></li>
  <li><%= link_to "Encomendas", encomendas_path %></li>
</ul>